version: '3.4'

services:

  #Redis Service
  redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  # Status Dashboard Service
  status-dashboard:
    image: juergenpointinger/status-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 5000:5000