version: '3.4'

services:

  # Status Dashboard Service
  status-dashboard:
    image: juergenpointinger/status-dashboard
    entrypoint: /bin/bash
    command: -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m index run --no-debugger --no-reload --host 0.0.0.0 --port 5000"
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_ENV=development
      - DEBUG=1
